//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountCalendarEvents = new HashSet<AccountCalendarEvent>();
            this.AccountFavSites = new HashSet<AccountFavSite>();
            this.AccountFriends = new HashSet<AccountFriend>();
            this.AccountFriends1 = new HashSet<AccountFriend>();
            this.AccountPhotoes = new HashSet<AccountPhoto>();
            this.AccountPosts = new HashSet<AccountPost>();
            this.AccountPosts1 = new HashSet<AccountPost>();
            this.AccountSkills = new HashSet<AccountSkill>();
            this.AccountVideos = new HashSet<AccountVideo>();
            this.Communications = new HashSet<Communication>();
            this.Communications1 = new HashSet<Communication>();
            this.Fora = new HashSet<Forum>();
            this.ForumMessages = new HashSet<ForumMessage>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string HerEmail { get; set; }
        public string HerPassword { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string ProfilePic { get; set; }
        public string BackgroundImage { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<bool> TokenExpired { get; set; }
        public Nullable<System.Guid> HerToken { get; set; }
        public Nullable<bool> HerTokenExpired { get; set; }
        public string WifesPageTitle { get; set; }
        public string WifesPageUrl { get; set; }
        public string ResumeFileName { get; set; }
        public string HeaderBackColor1 { get; set; }
        public string HeaderBackColor2 { get; set; }
        public string HeaderFontColor { get; set; }
        public string LeftPanelBackColor1 { get; set; }
        public string LeftPanelBackColor2 { get; set; }
        public string LeftPanelFontColor { get; set; }
        public string RightPanelBackColor1 { get; set; }
        public string RightPanelBackColor2 { get; set; }
        public string RightPanelFontColor { get; set; }
        public Nullable<int> MainPanelBackImgTransparency { get; set; }
        public Nullable<int> MainPanelPanelsTransparency { get; set; }
        public string MainPanelFontColor { get; set; }
        public string MancaveTile1Name { get; set; }
        public string MancaveTile1Url { get; set; }
        public string MancaveTile1Img { get; set; }
        public string MancaveTile2Name { get; set; }
        public string MancaveTile2Url { get; set; }
        public string MancaveTile2Img { get; set; }
        public string MancaveTile3Name { get; set; }
        public string MancaveTile3Url { get; set; }
        public string MancaveTile3Img { get; set; }
        public string MancaveTile4Name { get; set; }
        public string MancaveTile4Url { get; set; }
        public string MancaveTile4Img { get; set; }
        public string MancaveTile5Name { get; set; }
        public string MancaveTile5Url { get; set; }
        public string MancaveTile5Img { get; set; }
        public string MancaveTile6Name { get; set; }
        public string MancaveTile6Url { get; set; }
        public string MancaveTile6Img { get; set; }
        public string RadioEmbedCode { get; set; }
        public Nullable<int> RadioPosition { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<AccountCalendarEvent> AccountCalendarEvents { get; set; }
        public virtual ICollection<AccountFavSite> AccountFavSites { get; set; }
        public virtual ICollection<AccountFriend> AccountFriends { get; set; }
        public virtual ICollection<AccountFriend> AccountFriends1 { get; set; }
        public virtual ICollection<AccountPhoto> AccountPhotoes { get; set; }
        public virtual ICollection<AccountPost> AccountPosts { get; set; }
        public virtual ICollection<AccountPost> AccountPosts1 { get; set; }
        public virtual ICollection<AccountSkill> AccountSkills { get; set; }
        public virtual ICollection<AccountVideo> AccountVideos { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<Communication> Communications1 { get; set; }
        public virtual ICollection<Forum> Fora { get; set; }
        public virtual ICollection<ForumMessage> ForumMessages { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
