//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPost
    {
        public AccountPost()
        {
            this.AccountPost1 = new HashSet<AccountPost>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentAccountPostId { get; set; }
        public int AccountId { get; set; }
        public int PostedByAccountId { get; set; }
        public string PhotoFile { get; set; }
        public string VideoUrl { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PrivacyId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual ICollection<AccountPost> AccountPost1 { get; set; }
        public virtual AccountPost AccountPost2 { get; set; }
        public virtual Privacy Privacy { get; set; }
    }
}
