//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSkill
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Skill { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> LastUsed { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
