//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AccountPhotoes = new HashSet<AccountPhoto>();
            this.AccountVideos = new HashSet<AccountVideo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AccountPhoto> AccountPhotoes { get; set; }
        public virtual ICollection<AccountVideo> AccountVideos { get; set; }
    }
}
