//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int Id { get; set; }
        public Nullable<int> CommMethodId { get; set; }
        public int ActionId { get; set; }
        public int FromAcctId { get; set; }
        public int ToAcctId { get; set; }
        public int StatusToId { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public string SubjectTo { get; set; }
        public string MessageTo { get; set; }
        public string MessageToEmail { get; set; }
        public string MessageToTxtMsg { get; set; }
        public Nullable<bool> MessageToEmailSent { get; set; }
        public Nullable<bool> MessageToTxtMsgSent { get; set; }
        public Nullable<bool> Archived { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Action Action { get; set; }
        public virtual CommMethod CommMethod { get; set; }
        public virtual Status Status { get; set; }
    }
}
