//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessage
    {
        public ForumMessage()
        {
            this.ForumMessage1 = new HashSet<ForumMessage>();
        }
    
        public int Id { get; set; }
        public string Message { get; set; }
        public string PhotoFile { get; set; }
        public Nullable<int> ParentForumMessageId { get; set; }
        public int OwnerAccountId { get; set; }
        public int TopicId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<ForumMessage> ForumMessage1 { get; set; }
        public virtual ForumMessage ForumMessage2 { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
