//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MancaveEntities : DbContext
    {
        public MancaveEntities()
            : base("name=MancaveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountCalendarEvent> AccountCalendarEvents { get; set; }
        public DbSet<AccountFavSite> AccountFavSites { get; set; }
        public DbSet<AccountFriend> AccountFriends { get; set; }
        public DbSet<AccountPhoto> AccountPhotoes { get; set; }
        public DbSet<AccountPost> AccountPosts { get; set; }
        public DbSet<AccountSkill> AccountSkills { get; set; }
        public DbSet<AccountVideo> AccountVideos { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<Album> Albums { get; set; }
        public DbSet<CommMethod> CommMethods { get; set; }
        public DbSet<Communication> Communications { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Forum> Fora { get; set; }
        public DbSet<ForumMessage> ForumMessages { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<Privacy> Privacies { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Topic> Topics { get; set; }
    }
}
