//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancave.MancaveServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.ForumMessages = new HashSet<ForumMessage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OwnerAccountId { get; set; }
        public int ForumId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Forum Forum { get; set; }
        public virtual ICollection<ForumMessage> ForumMessages { get; set; }
    }
}
